openapi: 3.0.2
info:
  contact:
    email: thomas.schaffter@sagebionetworks.org
    name: The NLP Sandbox Team
    url: https://nlpsandbox.github.io/nlpsandbox-schemas
  description: |
    The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers.
    # Overview
    TBA
  license:
    name: Apache 2.0
    url: https://nlpsandbox.github.io/nlpsandbox-schemas/blob/develop/LICENSE
  title: NLP Sandbox Deidentifier API
  version: 0.3.1
  x-logo:
    url: https://nlpsandbox.github.io/nlpsandbox-schemas/logo.png
servers:
- url: http://example.com/api/v1
- url: https://example.com/api/v1
tags:
- description: Operations about deidentified notes
  name: DeidentifiedNotes
- description: Operations about health checks
  name: HealthCheck
- description: Operations about this tool
  name: Tool
paths:
  /deidentifiedNotes:
    post:
      description: Returns the deidentified note
      operationId: create_deidentified_notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeidentifyRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeidentifyResponse'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Deidentify a clinical note
      tags:
      - DeidentifiedNotes
      x-openapi-router-controller: openapi_server.controllers.deidentified_notes_controller
  /healthCheck:
    get:
      description: Get information about the health of the service
      operationId: get_health_check
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
          description: Success
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Get health check information
      tags:
      - HealthCheck
      x-openapi-router-controller: openapi_server.controllers.health_check_controller
  /tool:
    get:
      description: Get information about the tool
      operationId: get_tool
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
          description: Success
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Get tool information
      tags:
      - Tool
      x-openapi-router-controller: openapi_server.controllers.tool_controller
  /tool/dependencies:
    get:
      description: Get the dependencies of this tool
      operationId: get_tool_dependencies
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolDependencies'
          description: Success
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Get tool dependencies
      tags:
      - Tool
      x-openapi-router-controller: openapi_server.controllers.tool_controller
components:
  responses:
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Invalid request
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request cannot be fulfilled due to an unexpected server error
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The specified resource was not found
  schemas:
    DeidentificationConfig:
      description: Configuration of one deidentification strategy and a list of annotation
        types to apply it to.
      example:
        confidenceThreshold: 42.4
        deidentificationStrategy:
          redactConfig: '{}'
          annotationTypeConfig: '{}'
          maskingCharConfig:
            maskingChar: '*'
          dateOffsetConfig:
            offsetDays: 0
        annotationTypes:
        - text_physical_address
        - text_physical_address
      properties:
        confidenceThreshold:
          default: 0
          description: The minimum confidence level for a given annotation to be de-identified
          example: 42.4
          format: float
          maximum: 100
          minimum: 0
          type: number
        deidentificationStrategy:
          $ref: '#/components/schemas/DeidentificationConfig_deidentificationStrategy'
        annotationTypes:
          description: the types of annotations to which the de-identifer should apply
            the selected strategy
          items:
            enum:
            - text_physical_address
            - text_date
            - text_person_name
            type: string
          type: array
      type: object
    NoteResourceId:
      description: ID of the clinical note
      example: 507f1f77bcf86cd799439011
      type: string
    PatientResourceId:
      description: ID of the FHIR patient
      example: 507f1f77bcf86cd799439011
      type: string
    Note:
      description: A clinical note
      example:
        noteType: loinc:LP29684-5
        patientId: 507f1f77bcf86cd799439011
        id: 507f1f77bcf86cd799439011
        text: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott.
      properties:
        id:
          description: ID of the clinical note
          example: 507f1f77bcf86cd799439011
          type: string
        text:
          description: The content of the clinical note
          example: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott.
          type: string
        noteType:
          description: The note type (LOINC concept)
          example: loinc:LP29684-5
          type: string
        patientId:
          description: ID of the FHIR patient
          example: 507f1f77bcf86cd799439011
          type: string
      required:
      - noteType
      - text
      type: object
    DeidentifyRequest:
      description: A request to de-identify a note
      example:
        note:
          noteType: loinc:LP29684-5
          patientId: 507f1f77bcf86cd799439011
          id: 507f1f77bcf86cd799439011
          text: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott.
        deidentificationConfigurations:
        - confidenceThreshold: 42.4
          deidentificationStrategy:
            redactConfig: '{}'
            annotationTypeConfig: '{}'
            maskingCharConfig:
              maskingChar: '*'
            dateOffsetConfig:
              offsetDays: 0
          annotationTypes:
          - text_physical_address
          - text_physical_address
        - confidenceThreshold: 42.4
          deidentificationStrategy:
            redactConfig: '{}'
            annotationTypeConfig: '{}'
            maskingCharConfig:
              maskingChar: '*'
            dateOffsetConfig:
              offsetDays: 0
          annotationTypes:
          - text_physical_address
          - text_physical_address
      properties:
        deidentificationConfigurations:
          description: A list of deidentification strategies and the entity types
            on which to perform them. De-identification priority (i.e. which annotation
            to use when two annotations overlap) is determined by the order of this
            array and the order of the annotationTypes array inside of each deidentificationConfig.
          items:
            $ref: '#/components/schemas/DeidentificationConfig'
          type: array
        note:
          $ref: '#/components/schemas/Note'
      required:
      - note
      type: object
    AnnotationName:
      description: Resource name of the annotation record, of the form datasets/{datasetId}/annotationStores/{annotationStoreId}/annotations/{annotationId}
      example: datasets/awesome-dataset/annotationStores/awesome-annotation-store/annotations/507f1f77bcf86cd799439011
      type: string
    ResourceSource:
      description: An API resource source
      example:
        name: name
      properties:
        name:
          description: Full path of an API resource
          type: string
      type: object
    AnnotationSource:
      description: The source of an annotation record
      example:
        resourceSource:
          name: name
      properties:
        resourceSource:
          $ref: '#/components/schemas/ResourceSource'
      type: object
    TextAnnotation:
      description: An annotation in a text
      properties:
        start:
          description: The position of the first character
          example: 42
          type: integer
        length:
          description: The length of the annotation
          example: 10
          type: integer
        text:
          description: The string annotated
          type: string
        confidence:
          description: The confidence in the accuracy of the annotation
          example: 95
          format: float
          maximum: 100
          minimum: 0
          type: number
      required:
      - length
      - start
      - text
      type: object
    TextDateAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextDateAnnotation_allOf'
      description: A date annotation in a text
      example:
        start: 42
        length: 10
        text: 10/26/2020
        dateFormat: MM/DD/YYYY
      type: object
    TextPersonNameAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      description: A person name annotation in a text
      example:
        start: 42
        length: 11
        text: Chloe Price
      type: object
    TextPhysicalAddressAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextPhysicalAddressAnnotation_allOf'
      description: A person name annotation in a text
      example:
        start: 42
        length: 11
        text: Seattle
        addressType: city
      type: object
    Annotation:
      description: An annotation record
      example:
        textDateAnnotations:
        - start: 42
          length: 10
          text: 10/26/2020
          dateFormat: MM/DD/YYYY
        - start: 42
          length: 10
          text: 10/26/2020
          dateFormat: MM/DD/YYYY
        textPersonNameAnnotations:
        - start: 42
          length: 11
          text: Chloe Price
        - start: 42
          length: 11
          text: Chloe Price
        textPhysicalAddressAnnotations:
        - start: 42
          length: 11
          text: Seattle
          addressType: city
        - start: 42
          length: 11
          text: Seattle
          addressType: city
        annotationSource:
          resourceSource:
            name: name
        name: datasets/awesome-dataset/annotationStores/awesome-annotation-store/annotations/507f1f77bcf86cd799439011
      properties:
        name:
          description: Resource name of the annotation record, of the form datasets/{datasetId}/annotationStores/{annotationStoreId}/annotations/{annotationId}
          example: datasets/awesome-dataset/annotationStores/awesome-annotation-store/annotations/507f1f77bcf86cd799439011
          type: string
        annotationSource:
          $ref: '#/components/schemas/AnnotationSource'
        textDateAnnotations:
          description: Date annotations in a text
          items:
            $ref: '#/components/schemas/TextDateAnnotation'
          type: array
        textPersonNameAnnotations:
          description: Person name annotations in a text
          items:
            $ref: '#/components/schemas/TextPersonNameAnnotation'
          type: array
        textPhysicalAddressAnnotations:
          description: Physical address annotations in a text
          items:
            $ref: '#/components/schemas/TextPhysicalAddressAnnotation'
          type: array
      type: object
    DeidentifyResponse:
      description: Response to deidentification request
      example:
        deidentifiedAnnotations:
          textDateAnnotations:
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
          textPersonNameAnnotations:
          - start: 42
            length: 11
            text: Chloe Price
          - start: 42
            length: 11
            text: Chloe Price
          textPhysicalAddressAnnotations:
          - start: 42
            length: 11
            text: Seattle
            addressType: city
          - start: 42
            length: 11
            text: Seattle
            addressType: city
          annotationSource:
            resourceSource:
              name: name
          name: datasets/awesome-dataset/annotationStores/awesome-annotation-store/annotations/507f1f77bcf86cd799439011
        deidentifiedNote:
          noteType: loinc:LP29684-5
          patientId: 507f1f77bcf86cd799439011
          id: 507f1f77bcf86cd799439011
          text: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott.
        originalAnnotations:
          textDateAnnotations:
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
          textPersonNameAnnotations:
          - start: 42
            length: 11
            text: Chloe Price
          - start: 42
            length: 11
            text: Chloe Price
          textPhysicalAddressAnnotations:
          - start: 42
            length: 11
            text: Seattle
            addressType: city
          - start: 42
            length: 11
            text: Seattle
            addressType: city
          annotationSource:
            resourceSource:
              name: name
          name: datasets/awesome-dataset/annotationStores/awesome-annotation-store/annotations/507f1f77bcf86cd799439011
      properties:
        originalAnnotations:
          $ref: '#/components/schemas/Annotation'
        deidentifiedAnnotations:
          $ref: '#/components/schemas/Annotation'
        deidentifiedNote:
          $ref: '#/components/schemas/Note'
      type: object
    Error:
      description: Problem details (tools.ietf.org/html/rfc7807)
      properties:
        title:
          description: A human readable documentation for the problem type
          type: string
        status:
          description: The HTTP status code
          type: integer
        detail:
          description: A human readable explanation specific to this occurrence of
            the problem
          type: string
        type:
          description: An absolute URI that identifies the problem type
          type: string
      required:
      - status
      - title
      type: object
    HealthCheck:
      description: Represents the health of a service
      example:
        status: pass
      properties:
        status:
          description: Indicates whether the service status is acceptable or not
          enum:
          - pass
          - fail
          - warn
          type: string
      required:
      - status
      type: object
    License:
      description: License (license keyword used by GitHub)
      enum:
      - afl-3.0
      - apache-2.0
      - artistic-2.0
      - bsl-1.0
      - bsd-2-clause
      - bsd-3-clause
      - bsd-3-clause-clear
      - cc
      - cc0-1.0
      - cc-by-4.0
      - cc-by-sa-4.0
      - wtfpl
      - ecl-2.0
      - epl-1.0
      - epl-2.0
      - eupl-1.1
      - agpl-3.0
      - gpl
      - gpl-2.0
      - gpl-3.0
      - lgpl
      - lgpl-2.1
      - lgpl-3.0
      - isc
      - lppl-1.3c
      - ms-pl
      - mit
      - mpl-2.0
      - osl-3.0
      - postgresql
      - ofl-1.1
      - ncsa
      - unlicense
      - zlib
      example: apache-2.0
      type: string
    ToolType:
      description: Type of this tool
      example: nlpsandbox:date-annotator
      type: string
    Tool:
      description: Information about an NLP tool
      example:
        license: apache-2.0
        authorEmail: author@example.com
        author: Example Author
        name: awesome-date-annotator
        description: An awesome Date Annotator based on regex patterns
        repository: github:awesome-org/awesome-date-annotator
        version: 1.0.0
        toolType: nlpsandbox:date-annotator
        url: https://openapi-generator.tech
      properties:
        name:
          description: The tool name
          example: awesome-date-annotator
          maxLength: 60
          minLength: 3
          pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
          type: string
        version:
          description: The version of the tool (SemVer string)
          example: 1.0.0
          minLength: 1
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          type: string
        license:
          $ref: '#/components/schemas/License'
        repository:
          description: The place where the code lives
          example: github:awesome-org/awesome-date-annotator
          type: string
        description:
          description: A short, one-sentence summary of the tool
          example: An awesome Date Annotator based on regex patterns
          maxLength: 100
          type: string
        author:
          description: The author of the tool
          example: Example Author
          type: string
        authorEmail:
          description: The email address of the author
          example: author@example.com
          format: email
          type: string
        url:
          description: The URL to the homepage of the tool
          format: uri
          type: string
        toolType:
          description: Type of this tool
          example: nlpsandbox:date-annotator
          type: string
      required:
      - author
      - authorEmail
      - description
      - license
      - name
      - repository
      - toolType
      - url
      - version
      type: object
    ToolDependencies:
      description: A list of tool dependencies
      example:
        toolDependencies:
        - license: apache-2.0
          authorEmail: author@example.com
          author: Example Author
          name: awesome-date-annotator
          description: An awesome Date Annotator based on regex patterns
          repository: github:awesome-org/awesome-date-annotator
          version: 1.0.0
          toolType: nlpsandbox:date-annotator
          url: https://openapi-generator.tech
        - license: apache-2.0
          authorEmail: author@example.com
          author: Example Author
          name: awesome-date-annotator
          description: An awesome Date Annotator based on regex patterns
          repository: github:awesome-org/awesome-date-annotator
          version: 1.0.0
          toolType: nlpsandbox:date-annotator
          url: https://openapi-generator.tech
      properties:
        toolDependencies:
          description: A list of tools
          items:
            $ref: '#/components/schemas/Tool'
          type: array
      type: object
    DeidentificationConfig_deidentificationStrategy_maskingCharConfig:
      description: Configuration for the masking char strategy. E.g. "John Smith lives
        at 123 Main St" -> "********* lives at ***********".
      example:
        maskingChar: '*'
      properties:
        maskingChar:
          default: '*'
          description: Character used to mask annotated PII text.
          maxLength: 1
          minLength: 1
          type: string
      type: object
    DeidentificationConfig_deidentificationStrategy_dateOffsetConfig:
      description: Configuration for the "date offset" strategy. E.g. "John Smith
        visited on 1 January 2020" -> "John Smith visited on 29 October 2025". Note,
        can only be set with the "text_date" annotation type.
      example:
        offsetDays: 0
      properties:
        offsetDays:
          description: Number of days by which to offset annotated dates.
          type: integer
      type: object
    DeidentificationConfig_deidentificationStrategy:
      description: The strategy used to de-identify the note's text. Only one field
        may be set.
      example:
        redactConfig: '{}'
        annotationTypeConfig: '{}'
        maskingCharConfig:
          maskingChar: '*'
        dateOffsetConfig:
          offsetDays: 0
      properties:
        maskingCharConfig:
          $ref: '#/components/schemas/DeidentificationConfig_deidentificationStrategy_maskingCharConfig'
        redactConfig:
          description: Configuration for the redaction strategy. E.g. "John Smith
            lives at 123 Main St" -> "lives at".
          type: object
        annotationTypeConfig:
          description: Configuration for the "annotation type" strategy. E.g. "John
            Smith lives at 123 Main St" -> "[PERSON_NAME] lives at [PHYSICAL_ADDRESS]".
          type: object
        dateOffsetConfig:
          $ref: '#/components/schemas/DeidentificationConfig_deidentificationStrategy_dateOffsetConfig'
      type: object
    TextDateAnnotation_allOf:
      properties:
        dateFormat:
          description: Date format (ISO 8601)
          example: MM/DD/YYYY
          type: string
      type: object
    TextPhysicalAddressAnnotation_allOf:
      properties:
        addressType:
          description: Type of address information
          enum:
          - city
          - country
          - department
          - hospital
          - organization
          - other
          - room
          - state
          - street
          - zip
          type: string
      type: object
